// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Abp.TenantDomainManagement;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Abp.TenantDomainManagement;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITenantDomainAppService), typeof(TenantDomainClientProxy))]
public partial class TenantDomainClientProxy : ClientProxyBase<ITenantDomainAppService>, ITenantDomainAppService
{
    public virtual async Task<TenantDomainDto> ConnectAsync(ConnectTenantDomainInput input)
    {
        return await RequestAsync<TenantDomainDto>(nameof(ConnectAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ConnectTenantDomainInput), input }
        });
    }

    public virtual async Task<TenantDomainDto> GetAsync()
    {
        return await RequestAsync<TenantDomainDto>(nameof(GetAsync));
    }

    public virtual async Task<bool> CheckCnameRecordAsync(string domainName)
    {
        return await RequestAsync<bool>(nameof(CheckCnameRecordAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), domainName }
        });
    }
}
