export enum LanguagesMap {
    ar= 'ar',
    cs= 'cs',
    en= 'en-gb',
    hi= 'hi',
    fi= 'fi',
    hu= 'hu',
    fr= 'fr',
    it= 'it',
    'en-GB'= 'en-gb',
    'pt-BR'= 'pt-br',
    'zh-Hant'= 'zh',
    'zh-Hans'= 'zh-cn',
    tr= 'tr',
    sk= 'sk',
    'de-DE'= 'de',
    es= 'es',
    ja= 'ja',
    vi= 'vi',
}
