FROM mcr.microsoft.com/dotnet/aspnet:7.0  AS base
COPY bin/Release/net7.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep authserver.pfx -p d56d56b8-b1df-41ce-a102-9e8c458b58de

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "test_Item.HttpApi.Host.dll"]