// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.CmsKit.Public.Favourites;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.CmsKit.Public.Favourites;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFavouritePublicAppService), typeof(FavouritePublicClientProxy))]
public partial class FavouritePublicClientProxy : ClientProxyBase<IFavouritePublicAppService>, IFavouritePublicAppService
{
    public virtual async Task<FavouriteDto> CreateAsync(string entityType, string entityId)
    {
        return await RequestAsync<FavouriteDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), entityType },
            { typeof(string), entityId }
        });
    }

    public virtual async Task DeleteAsync(string entityType, string entityId)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), entityType },
            { typeof(string), entityId }
        });
    }
}
