// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.CmsKit.Public.Visits;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.CmsKit.Public.Visits;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IVisitPublicAppService), typeof(VisitPublicClientProxy))]
public partial class VisitPublicClientProxy : ClientProxyBase<IVisitPublicAppService>, IVisitPublicAppService
{
    public virtual async Task<VisitDto> CreateAsync(string entityType, string entityId, CreateVisitInput input)
    {
        return await RequestAsync<VisitDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), entityType },
            { typeof(string), entityId },
            { typeof(CreateVisitInput), input }
        });
    }
}
