blank_issues_enabled: true
contact_links:
  - name: Ask a question (community support)
    url:  https://stackoverflow.com/questions/tagged/abp
    about: Ask a question that will be answered by the ABP community
