// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Abp.LocaleManagement;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Abp.LocaleManagement;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ILocaleAppService), typeof(LocaleClientProxy))]
public partial class LocaleClientProxy : ClientProxyBase<ILocaleAppService>, ILocaleAppService
{
    public virtual async Task<LocaleDto> GetAsync()
    {
        return await RequestAsync<LocaleDto>(nameof(GetAsync));
    }

    public virtual async Task<LocaleDto> UpdateAsync(UpdateLocaleInput input)
    {
        return await RequestAsync<LocaleDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateLocaleInput), input }
        });
    }
}
