using Dignite.Abp.NotificationCenter.EntityFrameworkCore;

namespace Dignite.Abp.NotificationCenter;

public class NotificationSubscriptionRepository_Tests : NotificationSubscriptionRepository_Tests<DigniteAbpNotificationCenterEntityFrameworkCoreTestModule>
{
}