// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.FileExplorer.Directories;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.FileExplorer.Directories;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IDirectoryDescriptorAppService), typeof(FileDescriptorClientProxy))]
public partial class FileDescriptorClientProxy : ClientProxyBase<IDirectoryDescriptorAppService>, IDirectoryDescriptorAppService
{
    public virtual async Task<DirectoryDescriptorDto> CreateAsync(CreateDirectoryInput input)
    {
        return await RequestAsync<DirectoryDescriptorDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateDirectoryInput), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<DirectoryDescriptorDto> GetAsync(Guid id)
    {
        return await RequestAsync<DirectoryDescriptorDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<DirectoryDescriptorInfoDto>> GetListAsync(GetDirectoriesInput input)
    {
        return await RequestAsync<PagedResultDto<DirectoryDescriptorInfoDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetDirectoriesInput), input }
        });
    }

    public virtual async Task<ListResultDto<DirectoryDescriptorInfoDto>> GetMyAsync(string containerName)
    {
        return await RequestAsync<ListResultDto<DirectoryDescriptorInfoDto>>(nameof(GetMyAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), containerName }
        });
    }

    public virtual async Task<DirectoryDescriptorDto> MoveAsync(Guid id, MoveDirectoryInput input)
    {
        return await RequestAsync<DirectoryDescriptorDto>(nameof(MoveAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MoveDirectoryInput), input }
        });
    }

    public virtual async Task<DirectoryDescriptorDto> UpdateAsync(Guid id, UpdateDirectoryInput input)
    {
        return await RequestAsync<DirectoryDescriptorDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateDirectoryInput), input }
        });
    }
}
