// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Abp.UserPoints;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Abp.UserPoints;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMyPointAppService), typeof(MyPointClientProxy))]
public partial class MyPointClientProxy : ClientProxyBase<IMyPointAppService>, IMyPointAppService
{
    public virtual async Task<ListResultDto<UserPointAccountDto>> GetAccountsAsync()
    {
        return await RequestAsync<ListResultDto<UserPointAccountDto>>(nameof(GetAccountsAsync));
    }

    public virtual async Task<PagedResultDto<UserPointTransactionDto>> GetListAsync(GetUserPointTransactionsInput input)
    {
        return await RequestAsync<PagedResultDto<UserPointTransactionDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetUserPointTransactionsInput), input }
        });
    }
}
