// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Cms.Admin.Fields;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Cms.Admin.Fields;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFieldGroupAdminAppService), typeof(FieldGroupAdminClientProxy))]
public partial class FieldGroupAdminClientProxy : ClientProxyBase<IFieldGroupAdminAppService>, IFieldGroupAdminAppService
{
    public virtual async Task<FieldGroupDto> CreateAsync(CreateOrUpdateFieldGroupInput input)
    {
        return await RequestAsync<FieldGroupDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateOrUpdateFieldGroupInput), input }
        });
    }

    public virtual async Task<FieldGroupDto> UpdateAsync(Guid id, CreateOrUpdateFieldGroupInput input)
    {
        return await RequestAsync<FieldGroupDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(CreateOrUpdateFieldGroupInput), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<FieldGroupDto>> GetListAsync(GetFieldGroupsInput input)
    {
        return await RequestAsync<PagedResultDto<FieldGroupDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetFieldGroupsInput), input }
        });
    }

    public virtual async Task<FieldGroupDto> GetAsync(Guid id)
    {
        return await RequestAsync<FieldGroupDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
