// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Cms.Fields;
using Dignite.Cms.Public.Fields;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Cms.Public.Fields;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFieldPublicAppService), typeof(FieldPublicClientProxy))]
public partial class FieldPublicClientProxy : ClientProxyBase<IFieldPublicAppService>, IFieldPublicAppService
{
    public virtual async Task<FieldDto> FindByNameAsync(string name)
    {
        return await RequestAsync<FieldDto>(nameof(FindByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }
}
