// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

// ReSharper disable once CheckNamespace
namespace Dignite.Abp.SettingManagement.ClientProxies
{
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(ITenantSettingsAppService), typeof(TenantSettingsClientProxy))]
    public partial class TenantSettingsClientProxy : ClientProxyBase<ITenantSettingsAppService>, ITenantSettingsAppService
    {
        public virtual async Task<ListResultDto<SettingGroupDto>> GetAllAsync()
        {
            return await RequestAsync<ListResultDto<SettingGroupDto>>(nameof(GetAllAsync));
        }

        public virtual async Task UpdateAsync(UpdateTenantSettingsInput input)
        {
            await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
            {
                { typeof(UpdateTenantSettingsInput), input }
            });
        }
    }
}