// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.CmsKit.Admin.Brand;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.CmsKit.Admin.Brand;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBrandAdminAppService), typeof(BrandAdminClientProxy))]
public partial class BrandAdminClientProxy : ClientProxyBase<IBrandAdminAppService>, IBrandAdminAppService
{
    public virtual async Task UpdateAsync(UpdateBrandInput input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateBrandInput), input }
        });
    }
}
