namespace Dignite.Abp.RegionalizationManagement.EntityFrameworkCore;

public class EfCoreRegionalizationAppService_Tests : RegionalizationAppService_Tests<RegionalizationManagementEntityFrameworkCoreTestModule>
{

}
