name: Merge branch main with rel-1.0
on:
  push:
    branches:
      - rel-1.0
permissions:
  contents: read

jobs:
  merge-main-with-rel-1-0:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin rel-1.0:rel-1.0
          git reset --hard rel-1.0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-merge/rel-1-0/${{github.run_number}}
          title: Merge branch main with rel-1.0
          body: This PR generated automatically to merge main with rel-1.0. Please review the changed files before merging to prevent any errors that may occur.
          reviewers: ${{github.actor}}
          token: ${{ github.token }}
