name: Merge branch main with rel-3.0.0-rc.1
on:
  push:
    branches:
      - rel-3.0.0-rc.1
permissions:
  contents: read

jobs:
  merge-main-with-rel-1-8-3:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin rel-3.0.0-rc.1:rel-3.0.0-rc.1
          git reset --hard rel-3.0.0-rc.1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-merge/rel-3-0-0/${{github.run_number}}
          title: Merge branch main with rel-3.0.0-rc.1
          body: This PR generated automatically to merge main with rel-3.0.0-rc.1 Please review the changed files before merging to prevent any errors that may occur.
          reviewers: ${{github.actor}}
          token: ${{ github.token }}
      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.BOT_SECRET }}
        run: |
          gh pr review auto-merge/rel-8-3/${{github.run_number}} --approve
          gh pr merge auto-merge/rel-8-3/${{github.run_number}} --merge --auto --delete-branch

