// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.CmsKit.Public.MarkedItems;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.CmsKit.Public.MarkedItems;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMarkedItemPublicAppService), typeof(MarkedItemPublicClientProxy))]
public partial class MarkedItemPublicClientProxy : ClientProxyBase<IMarkedItemPublicAppService>, IMarkedItemPublicAppService
{
    public virtual async Task<ListResultDto<String>> GetListForUserAsync(string entityType)
    {
        return await RequestAsync<ListResultDto<String>>(nameof(GetListForUserAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), entityType }
        });
    }
}
